void initCommunication(void);
void sendPower();
void sendPower();
void sendVolUp();
void sendVolDown();
void sendProgramUp();
void sendProgramDown();
void sendOK();
void sendExit();
void sendNewDevice();
void getVolume();
void getFullStatus();
void freeArray(char **arr,int n);
